/**
 * Preset skills for talent onboarding / profile — checkbox list (aligned with TalentOnboarding pattern).
 */
export const TALENT_SKILL_OPTIONS = [
  "Agile / Scrum",
  "AWS / Cloud",
  "Blockchain",
  "Brand Design",
  "Business Development",
  "Content Strategy",
  "Customer Success",
  "Data Science",
  "DevOps",
  "Docker / Kubernetes",
  "Embedded Systems",
  "Finance",
  "Go",
  "GraphQL",
  "Growth / Growth Marketing",
  "HR / People Ops",
  "Java",
  "Kotlin",
  "Legal / Compliance",
  "LLMs / AI",
  "Machine Learning",
  "Marketing",
  "Mobile Development",
  "MongoDB",
  "Node.js",
  "Operations",
  "PostgreSQL",
  "Product Management",
  "Product Strategy",
  "Python",
  "QA / Testing",
  "React",
  "Rust",
  "Sales",
  "Security",
  "SEO",
  "Swift / iOS",
  "Team Leadership",
  "Technical Writing",
  "TypeScript",
  "UI/UX Design",
  "Video / Motion",
].sort((a, b) => a.localeCompare(b));

export const TALENT_SKILL_OPTION_SET = new Set(TALENT_SKILL_OPTIONS);
