/** Mirrors server/src/realtime/events.js — org dashboard listeners only. */
export const ORG_SOCKET_EVENTS = Object.freeze({
  MESSAGE_CREATED: "message:created",
  COHORT_UPDATED: "cohort:updated",
  COHORT_DELETED: "cohort:deleted",
  EVENT_CREATED: "event:created",
  EVENT_UPDATED: "event:updated",
  EVENT_DELETED: "event:deleted",
  EVENT_CANCELLED: "event:cancelled",
  RESOURCE_CREATED: "resource:created",
  RESOURCE_UPDATED: "resource:updated",
  RESOURCE_DELETED: "resource:deleted",
  MILESTONE_UPDATED: "milestone:updated",
  MILESTONE_DELETED: "milestone:deleted",
  DELIVERABLE_CREATED: "deliverable:created",
  DELIVERABLE_UPDATED: "deliverable:updated",
  DELIVERABLE_DELETED: "deliverable:deleted",
  DELIVERABLE_ARCHIVED: "deliverable:archived",
  ANNOUNCEMENT_CREATED: "announcement:created",
  ANNOUNCEMENT_UPDATED: "announcement:updated",
  ANNOUNCEMENT_DELETED: "announcement:deleted",
  ANNOUNCEMENT_READ: "announcement:read",
  COHORT_INVITATION_CHANGED: "cohort-invitation:changed",
});
