import { Router } from "express";
import activityRouter from "./activity.routes.js";
import agendaRouter from "./agenda.routes.js";
import authRouter from "./auth.routes.js";
import adminRouter from "./admin.routes.js";
import emailsRouter from "./emails.routes.js";
import migrationsRouter from "./migrations.routes.js";
import eventsRouter from "./events.routes.js";
import mentorsRouter from "./mentors.routes.js";
import announcementsRouter from "./announcements.routes.js";
import pollsRouter from "./polls.routes.js";
import debugRouter from "./debug.routes.js";
import cronRouter from "./cron.routes.js";
import deliverablesRouter from "./deliverables.routes.js";
import executionScoreRouter from "./executionScore.routes.js";
import foundersRouter from "./founders.routes.js";
import googleRouter from "./google.routes.js";
import healthRouter from "./health.routes.js";
import invitationsRouter from "./invitations.routes.js";
import messagesRouter from "./messages.routes.js";
import notificationsRouter from "./notifications.routes.js";
import uploadsRouter from "./uploads.routes.js";
import attachmentsRouter from "./attachments.routes.js";
import callsRouter from "./calls.js";
import organizationsRouter from "./organizations.routes.js";
import presenceRouter from "./presence.routes.js";
import talentRouter from "./talent.routes.js";
import teamMembersRouter from "./teamMembers.routes.js";
import usersRouter from "./users.routes.js";
import meetingsRouter from "./meetings.routes.js";
import performanceRouter from "./performance.routes.js";
import membershipsRouter from "./memberships.routes.js";
import publicRouter from "./public.routes.js";

const apiRouter = Router();

apiRouter.use(healthRouter);
apiRouter.use(publicRouter);
apiRouter.use(activityRouter);
apiRouter.use(authRouter);
apiRouter.use(usersRouter);
apiRouter.use(foundersRouter);
apiRouter.use(organizationsRouter);
apiRouter.use(invitationsRouter);
apiRouter.use(deliverablesRouter);
apiRouter.use(messagesRouter);
apiRouter.use(uploadsRouter);
apiRouter.use(attachmentsRouter);
apiRouter.use("/calls", callsRouter);
apiRouter.use(notificationsRouter);
apiRouter.use(agendaRouter);
apiRouter.use(executionScoreRouter);
apiRouter.use(presenceRouter);
apiRouter.use(googleRouter);
apiRouter.use(talentRouter);
apiRouter.use(teamMembersRouter);
apiRouter.use(cronRouter);
apiRouter.use(eventsRouter);
apiRouter.use(mentorsRouter);
apiRouter.use(announcementsRouter);
apiRouter.use(pollsRouter);
apiRouter.use(meetingsRouter);
apiRouter.use(performanceRouter);
apiRouter.use(membershipsRouter);
apiRouter.use(emailsRouter);
apiRouter.use(adminRouter);
apiRouter.use(migrationsRouter);
apiRouter.use(debugRouter);

export default apiRouter;
